# Generated by Django 6.0.1 on 2026-01-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(unique=True)),
                ('nom_comercial', models.CharField()),
                ('cif', models.CharField()),
                ('persona_contacte', models.CharField()),
                ('telefon', models.CharField()),
                ('email', models.CharField()),
                ('adreca_entrega', models.CharField()),
                ('poblacio', models.CharField()),
                ('codi_postal', models.CharField()),
                ('actiu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Albara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_albara', models.CharField(unique=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateTimeField()),
                ('estat', models.CharField(choices=[(0, 'PENDENT'), (1, 'EN_PREPARACIO'), (2, 'ENVIAT'), (3, 'ENTREGAT'), (4, 'CANCELAT')])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='mp_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAlbara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField()),
                ('quantitat', models.IntegerField()),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, null=True)),
                ('albara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mp_app.albara')),
            ],
        ),
    ]
